[project]
name = "clarity-finetune"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastparquet>=2025.12.0",
    "huggingface-hub>=1.3.1",
    "pandas>=2.3.3",
    "pyarrow>=22.0.0",
]
